---
title: "Talks & Events"
toc: true
---

## Upcoming Presentations

* **Phenomenology of PBH remnants** *[Black Holes & Cosmology Conference](https://indico.mpp.mpg.de/event/11604/overview)* — Granada, ES (Jun 15–19, 2026)

## Past Presentations & Seminars

* **Quantum Gravity and Primordial Black Holes** *Journal Club of the [Service de Physique Théorique](https://physth.ulb.be/activities.html)* — ULB, BE (Jun 5, 2026)
<br>[<i class="bi bi-file-earmark-slides"></i> Slides](./assets/talk_JC-ULB_20260605.pdf){.btn-surface .c-teal .btn-compact}

* **Signatures of LQG in PBH cosmologies** *[RER-S8 Cosmology Meeting](https://indico.global/event/18104/)* — UCLouvain, BE (May 26, 2026)
<br>[<i class="bi bi-file-earmark-slides"></i> Slides](./assets/talk_RERS8_20260526.pdf){.btn-surface .c-teal .btn-compact}

* **Constraining PBH remnants with LISA and cosmological observables** *LISA Madrid Group Meeting* — Madrid, ES (Apr 9, 2026)
<br>[<i class="bi bi-file-earmark-slides"></i> Slides](./assets/talk_LISA-Madrid_20260409.pdf){.btn-surface .c-teal .btn-compact}

* **Signatures of LQG in PBH cosmologies** *Group Meeting Presentation* — IEM-CSIC, Madrid, ES (Mar 30, 2026)  
<!-- <br>[<i class="bi bi-file-earmark-slides"></i> Slides](./assets/talk_LQG-PBH_20260330.pdf){.btn-surface .c-teal .btn-compact} -->

* **Group introduction on Causal Spinfoams** *[ILQGS](https://relativity.phys.lsu.edu/ilqgs/) Group Intro Session* — IEM-CSIC, Madrid, ES (Feb 2, 2026)
<br>[<i class="bi bi-file-earmark-slides"></i> Slides](./assets/talk_Intro-ILQGS_20260202.pdf){.btn-surface .c-teal .btn-compact}