---
title: "Some useful links for physics students"
author: "Antoine Dierckx"
date: "2026-05-21"
categories: [resources, physics, tools]
---
# Some useful links for physics students
This page brings together some of the resources I have found most useful. The list is personal, but I hope it can also be useful to other students and researchers.

## 1. Foundations & Lecture Notes
These are some of the best resources I know for learning or revisiting the essentials:

* **[David Tong - Lecture Notes](http://www.damtp.cam.ac.uk/user/tong/teaching.html):** The definitive standard for clear, rigorous introductions to everything from Classical Dynamics to Quantum Field Theory.
* **[The Feynman Lectures on Physics](https://www.feynmanlectures.caltech.edu/):** Old but gold.
* **[Paul's Online Math Notes](https://tutorial.math.lamar.edu/):** High school level.
* **[MIT OpenCourseWare](https://ocw.mit.edu/):** Check out the course on general relativity, it's fantastic.
* **[LibreTexts Physics](https://phys.libretexts.org/Bookshelves):** Peer-authored, open-access textbook content.

## 2. Advanced Lectures & Seminars
If like me the reviews on arXiv make you a bit anxious, these are a great way to get a more digestible overview of the latest developments in various topics:

* **[Perimeter Institute (PIRSA)](https://pirsa.org/):** A massive archive of recorded seminars and specialized courses.
* **[Collège de France - Physique et Chimie](https://www.youtube.com/@Physique-Chimie-CdF/playlists):** High-level academic seminars and colloquia.
* **[General Relativity II (Piotr Chruściel)](https://youtube.com/playlist?list=PL2sWi-Ow64wd1xB58nyyeVU3BmpUL0e-E&si=HV_kqgQbqcfOnEwU):** All about black holes.
* **[Les Samedis de la Physique (Bruxelles)](https://www.saphybru.com/):** High-quality lectures from ULB professors.


## 3. Career Growth: Internships & Research
If you're looking to do early research or find internships, check out these resources:

* **[CERN Summer Student Programme](https://careers.cern/summer):** Particle physics stuff in Geneva.
* **[DESY Summer Student Programme](https://summerstudents.desy.de/):** Particle physics stuff in Hamburg.
* **[ESA Student Internships](https://www.esa.int/About_Us/Careers_at_ESA/Student_Internships2):** Space science at the European Space Agency.
* **[PSI Start (Perimeter Institute)](https://perimeterinstitute.ca/training/undergraduate-program/psi-start-research-internship):** Theoretical physics research at Perimeter Institute in Canada.

## 4. Free books
All the nice textbooks for free, because knowledge should be free:

* **[Sci-Hub](https://shadowlibraries.github.io/DirectDownloads/academicpapers/):** For academic papers.
* **[Library Genesis](https://shadowlibraries.github.io/DirectDownloads/libgen/)** and **[Anna's Archive](https://shadowlibraries.github.io/DirectDownloads/AnnasArchive/):** For books.
